name: renderbook

on:
  push:
    branches:
      - master
      - develop

jobs:
  bookdown:
    runs-on: ubuntu-latest  
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    container: 
      image: pecan/depends:R4.1

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install rmarkdown
        run: |
          Rscript -e 'install.packages(c("rmarkdown","bookdown"))'

      - name: Copy extfiles
        run: |
          mkdir -p book_source/extfiles
          cp -f documentation/tutorials/01_Demo_Basic_Run/extfiles/* book_source/extfiles

      - name: Build needed modules
        run: |
          R CMD INSTALL base/logger
          R CMD INSTALL base/remote
          R CMD INSTALL base/utils

      - name: Render Book
        run: |
          cd book_source
          Rscript -e 'options(bookdown.render.file_scope=FALSE); bookdown::render_book("index.Rmd", "bookdown::gitbook")'

      - name: Save artifact
        uses: actions/upload-artifact@v3
        with:
          name: pecan-documentation
          path: book_source/_book/

      - name: Checkout documentation repo
        if: github.event_name == 'push' && github.ref_type == 'branch'
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/pecan-documentation
          path: pecan-documentation
          token: ${{ secrets.GH_PAT }}

      - name: Publish to GitHub
        if: github.event_name == 'push' && github.ref_type == 'branch'
        run: |
          git config --global user.email "pecanproj@gmail.com"
          git config --global user.name "GitHub Documentation Robot"
          export VERSION=${GITHUB_REF##*/}
          cd pecan-documentation
          mkdir -p $VERSION
          rsync -a --delete ../book_source/_book/ ${VERSION}/
          git add --all *
          git commit -m "Build book from pecan revision ${GITHUB_SHA}" || true
          git push -q origin master
